### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront クライアントのセキュリティは、固定ライフサイクルポリシーに従います。
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908800"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront クライアントのセキュリティは、 [固定](/lifecycle/policies/fixed) ライフサイクルポリシーに従います。


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>リンク \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront クライアントのセキュリティは廃止されました。 サポートは、2015年7月14日に終了します。 製品バージョンのサポート終了後に、マルウェア対策およびスパイウェア対策の定義の更新プログラムは利用できなくなります。 システムセンターエンドポイントの保護を代替として評価してください。"
