### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 Configuration Manager
  description: Microsoft System Center 2012 Configuration Manager は、固定ライフサイクル ポリシーに従います。
  ms.date: 03/12/2021
  keywords: null
name: Microsoft System Center 2012 Configuration Manager
summary: |+
  Microsoft System Center 2012 Configuration Manager は、[固定](/lifecycle/policies/fixed)ライフサイクル ポリシーに従います。


products:
  - msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
  - version: Service Pack 2
    startDate: 05/12/2015
    endDate: 07/12/2022
  - version: Service Pack 1
    startDate: 12/15/2012
    endDate: 07/12/2016
  - version: Original Release
    startDate: 05/30/2012
    endDate: 01/14/2014
content: |+

  ## <a name="links"></a>リンク 
  * [Service Pack ポリシー](/lifecycle/policies/fixed#service-packs)
  * [System Center ドキュメント](/system-center/#pivot=components&panel=components-all)
  * [System Center リソース](https://www.microsoft.com/system-center/resources)
  * [移行ガイダンス](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)