### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront クライアントのセキュリティは、固定ライフサイクルポリシーに従います。
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924261"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront クライアントのセキュリティは、 [固定](/lifecycle/policies/fixed) ライフサイクルポリシーに従います。


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>リンク \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront クライアントのセキュリティは、2015年7月14日の時点で廃止されました。 製品バージョンのサポート終了後に、マルウェア対策およびスパイウェア対策の定義の更新プログラムは利用できなくなります。 システムセンターエンドポイントの保護を代替として評価してください。"
