### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security は、固定ライフサイクル ポリシーに従います。
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113414"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security は、[固定](/lifecycle/policies/fixed)ライフサイクル ポリシーに従います。


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>リンク \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security は、2015 年 7 月 14 日をもって廃止されました。 Antimalware および Antispyware の定義の更新プログラムは、製品バージョンのサポート終了後は利用できなくなります。 代わりとして System Center Endpoint Protection を評価してください。"
