### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization は、固定ライフサイクル ポリシーに従います。
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "825358"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization は、[固定](/lifecycle/policies/fixed)ライフサイクル ポリシーに従います。


  これは次のエディションに適用されます。4.1 for Desktops、4.2 for Desktops、for Terminal Services 4.1


  > [!IMPORTANT]

  > サポートは終了しました。 以下の移行ガイダンスを参照してください。
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>リンク \n* [移行ガイダンス](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>エディション \n* 4.1 for Desktops\n* 4.2 for Desktops\n* for Terminal Services 4.1"
